---
role_name_check: 1
dependency:
  name: galaxy
  options:
    ignore-certs: true
    ignore-errors: true
    role-file: requirements_dev.yml
    requirements-file: requirements.yml
    force: ${SLINGNODE_FORCE:-true}


driver:
  name: vagrant
  provider:
    name: libvirt
  provision: false
  cachier: machine
  parallel: true
  default_box: '${SLINGNODE_BOX:-generic/ubuntu2204}'


platforms:
  - name: instance
    hostname: slingnode-test-01
    config_options:
      ssh.keep_alive: true
      ssh.remote_user: 'vagrant'
      synced_folder: false
    memory: 4096
    cpus: 4
    provider_options:
      video_type: 'vga'
      driver: 'kvm'
      cpu_mode: 'host-passthrough'
      video_vram: '16384'


provisioner:
  name: ansible
  env:
    ANSIBLE_PIPELINING: "True"
  playbooks:
    converge: ../resources/playbooks/converge.yml
    # Using dedicated prepare playbook because Nimbus Validator requires
    # a running Consensus node in order to start
    prepare: ../resources/playbooks/prepare_nimbus_slashing_db.yml
  inventory:
    group_vars:
      all:
        clients:
          validator: nimbus
        export_slashing_protection_db: true


verifier:
  name: ansible


scenario:
  name: nimbus_export_slashing_protection_db
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
