---
- name: Copy slashing protection db to the server
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ validator_client_user.user }}"
    group: "{{ validator_client_group.group }}"
    mode: '0600'
  loop:
    - src: "{{ source_slashing_protection_db_to_copy }}"
      dest: "{{ host_slashing_protection_db_file }}"
  when: copy_slashing_protection_db_to_server | bool


- name: Copy docker-compose file
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0600'
  loop:
    - src: dc-blockchain-eth-validator-{{ clients.validator }}-mgmt.yml.j2
      dest: "{{ blockchain_docker_compose_path }}/dc-blockchain-eth-validator-{{ clients.validator }}-mgmt.yml"


- name: Stop validator container
  community.docker.docker_container:
    name: "{{ container_name_validator }}"
    state: stopped
  when: clients.validator == "prysm"


- name: Import slashing protection db
  community.docker.docker_compose:
    project_src: "{{ blockchain_docker_compose_path }}"
    files:
      - dc-blockchain-eth-validator-{{ clients.validator }}-mgmt.yml
    remove_orphans: false
    profiles:
      - import-slashing-protection-db
  register: output


- name: Docker output
  ansible.builtin.debug:
    var: output


- name: Start validator container
  community.docker.docker_container:
    name: "{{ container_name_validator }}"
    state: started
  when: clients.validator == "prysm"
