---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:

    - name: Ensure public key exists in slashing_protection.sqlite
      ansible.builtin.shell: |
        set -euxo pipefail && cat /opt/blockchain/validator/lighthouse/validators/slashing_protection.sqlite
      args:
        executable: /bin/bash
      register: shell_command_output
      changed_when: shell_command_output.rc == 0


    - name: Verify asserts
      ansible.builtin.assert:
        that:
          - shell_command_output.stdout.find("0x876a9a7fadb5b9d2114a5180f9fe50b451cbab5f241b42e476b724a3575e5a8277767bc5a7c831c63f066a9a725c") != -1
