---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:

    - name: Ensure slashing protection record has been created
      ansible.builtin.shell: |
        set -euxo pipefail && cat /opt/blockchain/validator/teku/validator/slashprotection/876a9a7fadb5b9d2114a5180f9fe50b451cbab5f241b42e476b724a3575e5a8277767bc5a7c831c63f066a9a725c53d6.yml
      args:
        executable: /bin/bash
      register: shell_command_output
      changed_when: shell_command_output.rc == 0
      until: "shell_command_output is not failed"
      retries: 20
      delay: 3


    - name: Verify asserts
      ansible.builtin.assert:
        that:
          - shell_command_output.stdout.find("0x043db0d9a83813551ee2f33450d23797757d430911a9320530ad8a0eabc43efb") != -1
