---
role_name_check: 1
dependency:
  name: galaxy
  options:
    ignore-certs: true
    ignore-errors: true
    role-file: requirements_dev.yml
    requirements-file: requirements.yml
    force: ${SLINGNODE_FORCE:-true}


driver:
  name: vagrant
  provider:
    name: libvirt
  provision: false
  cachier: machine
  parallel: true
  default_box: '${SLINGNODE_BOX:-generic/ubuntu2204}'


platforms:
  - name: instance
    hostname: slingnode-test-01
    config_options:
      ssh.keep_alive: true
      ssh.remote_user: 'vagrant'
      synced_folder: false
    memory: 4096
    cpus: 4
    provider_options:
      video_type: 'vga'
      driver: 'kvm'
      cpu_mode: 'host-passthrough'
      video_vram: '16384'


provisioner:
  name: ansible
  env:
    ANSIBLE_PIPELINING: "True"
  playbooks:
    # Using dedicated coverge playbook in order to scope variable to the converge stage
    # if export_slashing_protection_db is specifed here it is inlcuded in the scope
    # for the prepare stage which is not desired
    converge: ../resources/playbooks/converge_slashing_protection_db_export.yml
    prepare: ../resources/playbooks/prepare_slashing_db.yml
  inventory:
    group_vars:
      all:
        clients:
          validator: teku
        # Specifed in local converge.yml
        # export_slashing_protection_db: true


verifier:
  name: ansible


scenario:
  name: teku_export_slashing_protection_db
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
