---
- name: Converge
  hosts: all
  become: true
  gather_facts: false


  vars:
    export_slashing_protection_db: true


  tasks:
    - name: "Include slingnode-ansible-ethereum-node-mgmt"
      ansible.builtin.include_role:
        name: "slingnode-ansible-ethereum-node-mgmt"
