---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:

    - name: Include test tasks
      ansible.builtin.include_tasks:
        file: ../resources/tests/export_slashing_protection_db.yml
